[DEV-572] Написать инструкцию по анализу файла дампов
inelsy/QCrashHandler pull request #2
Opened 2024-03-24 10:12 UTC by kuzk0

FIX: breakpad submodule of inelsy

2024-03-27 19:14 UTC, vasilij-inelsy approved these changes

2024-03-27 19:15 UTC, vasilij-inelsy commented
Спасибо за МР!

Может сквашенм два коммита в один?

2024-03-27 19:19 UTC, kuzk0 commented
Да, так и будет, но со следующим коммитом (пока не запушил)

2024-03-31 12:54 UTC, vasilij-inelsy commented
Спасибо за инструкцию и clean up!

Давай сквашнем и можно мержить.

2024-04-01 09:35 UTC, sanych420 requested changes
Попытался пройти весь путь на Windows и Linux (см. замечания). В первом случае встрял на пункте с вызовом cv2pdb. Во втором - полученный файл result.txt не имел в себе информации о строке, вызвавшей падение.
Код тестового проекта и прочие файлы могу при необходимости скинуть.

Также считаю, что ряд шагов в инструкции пропущен. Я со всем этим уже занимался, поэтому представляю, что и как должно происходить, даже если что-то не расписано. Но если попросить менее погруженного человека пройтись по тексту и выполнить указания, то у него могут возникнуть проблемы. Поэтому прежде чем дать аппрув, прошу Анатолия прочитать readme и дать свою оценку полноте содержания.

2024-04-01 09:35 UTC, sanych420 commented on README.md
> +-  Включить `qdumper.pri` в ваш *.pro файл проекта
Не хватает информации о том, как правильно подключать папку с qcrashhandler. Просто скопировать весь репозиторий в свой проект? Тогда #include (строка 11) не пройдет, т.к. папка с репозиторием называется QCrashHandler, а не qcrashhandler. С использованием сабмодуля? Тогда это тоже надо описать

2024-04-01 09:35 UTC, sanych420 commented on README.md
> +- Включить заголовочный файл `qdumper.h` в точку входу вашего проекта
Пояснить, что имеется в виду файл main.cpp, а то не для всех может быть очевидно

2024-04-01 09:35 UTC, sanych420 commented on README.md
> +    /*или*/ QDumper Dumper("pathToDumpsFolder"); //установить путь для сохранения дампов
Так не проходит, нужно явно создать объект std::optional<QString> и передать на него указатель. Зачем так извращаться, кстати?

2024-04-01 09:35 UTC, sanych420 commented on README.md
> +    cv2pdb.exe PROJECT.exe
В каком режиме должен быть скомпилирован PROJECT.exe? Debug, release?
Есть ли разница, где должны лежать cv2pdb и PROJECT.exe?
Скомпилировал в release, положил полученный экзешник в папку рядом с cv2pdb.exe, запустил его, получил ошибку "cannot create PDB file".
Соответственно, дальше продвинуться не могу.

2024-04-01 09:35 UTC, sanych420 commented on README.md
> +    deps/breakpad.git/src/tools/linux/binaries/dump_syms PROJECT > PROJECT.sym
Папки binaries нет

2024-04-01 09:35 UTC, sanych420 commented on README.md
> +    *63D1AC58C4A2CBA81511319C65247FE90 - это случайный номер сборки `BUILD_ID` вашего проекта PROJECT*
Для вычленения номера сборки предлагаю команду `head -n 1 PROJECT.sym | awk '{print $4}'`

2024-04-01 09:35 UTC, sanych420 commented on README.md
> +    mkdir ./PROJECT.pdb/BUILD_ID/PROJECT.sym
`mkdir -p`, иначе не создаст весь путь

2024-04-01 09:35 UTC, sanych420 commented on README.md
> +minidump_stackwalk.exe file.dmp /path/To/SYMDIR/ [flags] > result.txt
Либо написать для Linux аналогичную строку, либо убрать '.exe'.

Плюс, подразумевается, что minidump_stackwalk находится по одному из известных путей, либо лежит рядом с файлом dmp. Это тоже надо бы прописать.

2024-04-01 12:53 UTC, AFF36 commented
1. Можно создать объект с моим путем для дампов или дефолтным, так? А дефолтный-то какой?

2024-04-01 13:25 UTC, AFF36 commented
2. Можно создать объект с родителем или без. В каком случае надо указывать с ним, а когда можно обойтись без этого?
3. Создание из .exe .pdb. Так мне надо по ссылке перейти в репозиторий https://github.com/rainers/cv2pdb, клонировать его себе, прочитать их readme, забилдить себе cv2pdb.exe? Или можно в этот репозиторий просто добавить уже готовый cv2pdb.exe? Если это уже сделано, то надо об этом написать в readme. Аналогично для .sym
4.  Вообще раздел "Сборка проекта на mingw" можно в начале написать в общих словах. Какая цель действий в этом разделе? Как-то все спутанно. Я так понимаю надо из .exe делать .pdb и .sym? Так напишите это
5. раздел "Сборка проекта на mingw" - каждый пункт начинается с цифры 1

2024-04-05 14:37 UTC, kuzk0 commented
> 5. раздел "Сборка проекта на mingw" - каждый пункт начинается с цифры 1

- В github и visual studio code список в файле интерпретируется нормально, каждый пункт пронумерован последовательно (1,2,3,4).
В тексте каждый пункт начинается с 1 для принадлежности к одному нумерованному списку. 
Ссылка на синтаксис нумерованного списка в markdown: https://learn.microsoft.com/ru-ru/azure/devops/project/wiki/markdown-guidance?view=azure-devops#ordered-or-numbered-lists

2024-04-14 16:52 UTC, merged